language: node_js
node_js:
- '9'
before_install:
  - openssl aes-256-cbc -K $encrypted_8bf6d2e253b3_key -iv $encrypted_8bf6d2e253b3_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
before_script:
- npm install
script:
- node index.js
notifications:
  slack: diginamic:nIQwPkWk2zfq2fjtzxMWhuBD#travis-atelier